sudo: required

language: python
python:
   - "2.7"

services:
   - docker

before_install:

   - docker pull rsquarelabs/framework-denv:beta
   - docker run rsquarelabs/framework-denv:beta

script:
  - uname
  - pip install -r requirements/dev-requirements.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)

