sudo: false

language: python
python:
   - "2.7"

services:
   - docker

before_install:

   - docker pull rsquarelabs/framework-denv:beta
   - docker run rsquarelabs/framework-denv:beta

install :
   - pip install tox-travis
   - pip install -r requirements/dev-requirements.txt
   - pip install  codecov
   - pip install coverage
   - python setup.py install
script:
   - tox

after_success:
  - codecov

