language: python
python:
    - "2.7"



before_install:
  - sudo yum update -y
  - sudo yum install gromacs
  # - sudo apt-get update && sudo apt-get install -y wget build-essential cmake file libxml2-dev libboost-dev
  # - wget ftp://ftp.gromacs.org/pub/gromacs/gromacs-5.0.4.tar.gz
  # - tar -xf gromacs-5.0.4.tar.gz
  # - cd gromacs-5.0.4
  # - mkdir build
  # - cd build/
  # - cmake .. -DGMX_BUILD_OWN_FFTW=ON -DREGRESSIONTEST_DOWNLOAD=ON
  # - make -j
  # - sudo make install
  # - cd /root
  # - echo source /usr/local/gromacs/bin/GMXRC >> .profile
  # - pip install codecov

script:
  - mdrun -v

after_success:
  - codecov
