language: python
python:
    - "2.7"



before_install:
  - sudo apt-get update && sudo apt-get install -y wget build-essential cmake file libxml2-dev libboost-dev
  - wget ftp://ftp.gromacs.org/pub/gromacs/gromacs-5.0.4.tar.gz
  - echo "c177ae5fd6d71e2bec7369bc66cd082e gromacs-5.0.4.tar.gz" > MD5SUM
  - md5sum -c MD5SUM
  - tar -xf gromacs-5.0.4.tar.gz
  - cd gromacs-5.0.4
  - mkdir build
  - cd build/
  - cmake .. -DGMX_BUILD_OWN_FFTW=ON -DREGRESSIONTEST_DOWNLOAD=ON
  - make -j
  - sudo make install
  - cd /root
  - echo source /usr/local/gromacs/bin/GMXRC >> .profile
  - pip install codecov

script:
  - mdrun -v

after_success:
  - codecov
