site_name: R2-CORE Framework
site_url: http://docs.rsquarelabs.com/sdk/framework
repo_url: https://github.com/rsquarelabs/framework
theme_dir : docs_theme
docs_dir: docs
use_directory_urls: true

markdown_extensions:
 - toc:
    anchorlink: True

pages:
- Home: index.md
- Tutorial:
    - Quickstart : user/tutorial/quickstart.md
- Dev Guides:
    - Project : developer/modules/project.md
    - Gromacs : developer/modules/gromacs.md
    - Documentation : developer/documentation.md
    - Environment Setup: developer/setting-environment.md


copyright: Copyright &copy; 2016 <a href="https://twitter.com/rrmerugu">rsquarelabs.com</a>
google_analytics: ['UA-71847416-1', 'docs.rsquarelabs.com']
