site_name: RSQUARELABS CORE
site_url: http://docs.rsquaelabs.org
docs_dir: docs
pages:
- Home: index.md
- Tutorials:
    - RSQ-GROMACS: tutorials/rsq-gromacs.md
    - RSQ-QSAR: tutorials/rsq-qsar.md
    - RSQ-MOLECULAR-VIEWER: tutorials/rsq-molecular-viewer.md
- Dev Notes:
    - Coding: /dev-notes/coding.md

theme: readthedocs