site_name: RSQUARELABS CORE
site_url: http://docs.rsquarelabs.org
canonical_url: http://docs.rsquarelabs.org
docs_dir: docs
pages:
- Home: index.md
- Tutorials:
    - RSQ-GROMACS: tutorials/rsq-gromacs.md
    - RSQ-QSAR: tutorials/rsq-qsar.md
    - RSQ-MOLECULAR-VIEWER: tutorials/rsq-molecular-viewer.md
- Dev Notes:
    - Coding: devnotes/coding.md

theme: readthedocs
copyright: Copyright &copy; 2016 <a href="https://twitter.com/rrmerugu">Ravi RT Merugu</a>
google_analytics: ['UA-71847416-1', 'rsquarelabs.org']